# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
rojo = "rojo-rbx/rojo@7.3.0"
wally = "upliftgames/wally@0.3.2"
selene = "kampfkarren/selene@0.25.0"
stylua = "johnnymorganz/stylua@0.18.1"
