[package]
name = "evaera/cmdr"
description = "Extensible command console for Roblox developers"
version = "1.12.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["assets", "docs"]

[dependencies]
